name: iTwin Demo Portal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    environment:
      name: CI

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        registry-url: https://registry.npmjs.org/

    - run: yarn install

    - run: yarn build
      # https://create-react-app.dev/docs/advanced-configuration/
      # https://github.com/imodeljs/create-react-app/blob/imodeljs/packages/react-scripts/README-imodeljs.md
      env:
        GENERATE_SOURCEMAP: false
        USE_FAST_SASS: true
        TRANSPILE_DEPS: false
        DISABLE_TERSER: true

    # - run: yarn test
